package natsconfig

import (
	"fmt"
	"sort"
	"strings"
)

// sentinelNKey is a syntactically-valid throwaway NATS user public key.
// It exists only to flip NATS into "auth required" mode when no real users
// are provisioned yet. The user has deny-all permissions, so even possession
// of the seed grants no access — the goal is to prevent anonymous $G clients,
// not to authenticate anyone.
const sentinelNKey = "UCIDQZZKASESVE5OOIFA3HJAQNSHYMUOSFPKY4FTDKMWNVIO4JW4Q5Q6"

// Generate produces a NATS server auth configuration string from the given config.
//
// Safe-by-default: if no users are provisioned in any account, a deny-all
// sentinel user is injected into the global $G account. Without this, NATS
// would treat the configuration as "no auth required" and route anonymous
// clients to $G with full access. The sentinel is stable across calls so
// it does not cause reconcile churn.
func Generate(cfg *NatsConfig) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by nats-operator - DO NOT EDIT\n")

	accounts := cfg.Accounts
	if totalUsers(accounts) == 0 {
		b.WriteString("# WARNING: no NatsUser resources defined. Emitting deny-all sentinel\n")
		b.WriteString("# in $G to force NATS to require authentication. Provision NatsUser\n")
		b.WriteString("# resources to enable real client access.\n")
		accounts = withSentinelAccount(accounts)
	}

	b.WriteString("accounts {\n")

	if accounts != nil {
		// Sort account names for deterministic output
		names := make([]string, 0, len(accounts))
		for name := range accounts {
			names = append(names, name)
		}
		sort.Strings(names)

		for _, name := range names {
			acct := accounts[name]
			writeAccount(&b, name, &acct, 1)
		}
	}

	b.WriteString("}\n")
	return b.String()
}

func totalUsers(accounts map[string]AccountConfig) int {
	n := 0
	for _, a := range accounts {
		n += len(a.Users)
	}
	return n
}

// withSentinelAccount returns a copy of accounts with a $G entry containing
// the deny-all sentinel user. The input map is not modified.
func withSentinelAccount(accounts map[string]AccountConfig) map[string]AccountConfig {
	out := make(map[string]AccountConfig, len(accounts)+1)
	for k, v := range accounts {
		out[k] = v
	}
	denyAll := []string{">"}
	out["$G"] = AccountConfig{
		Users: []UserConfig{
			{
				NKey: sentinelNKey,
				Permissions: &PermissionsConfig{
					Publish:   &PermissionRuleConfig{Deny: denyAll},
					Subscribe: &PermissionRuleConfig{Deny: denyAll},
				},
			},
		},
	}
	return out
}

func writeAccount(b *strings.Builder, name string, acct *AccountConfig, indent int) {
	prefix := strings.Repeat("  ", indent)
	fmt.Fprintf(b, "%s%s {\n", prefix, name)

	if acct.JetStream != nil {
		writeJetStream(b, acct.JetStream, indent+1)
	}

	if acct.Limits != nil {
		writeLimits(b, acct.Limits, indent+1)
	}

	if len(acct.Users) > 0 {
		writeUsers(b, acct.Users, indent+1)
	}

	fmt.Fprintf(b, "%s}\n", prefix)
}

func writeJetStream(b *strings.Builder, js *JetStreamConfig, indent int) {
	prefix := strings.Repeat("  ", indent)
	inner := strings.Repeat("  ", indent+1)

	fmt.Fprintf(b, "%sjetstream {\n", prefix)

	if js.MaxMemory != "" {
		fmt.Fprintf(b, "%smax_mem: %s\n", inner, js.MaxMemory)
	}
	if js.MaxFile != "" {
		fmt.Fprintf(b, "%smax_file: %s\n", inner, js.MaxFile)
	}
	if js.MaxStreams != nil {
		fmt.Fprintf(b, "%smax_streams: %d\n", inner, *js.MaxStreams)
	}
	if js.MaxConsumers != nil {
		fmt.Fprintf(b, "%smax_consumers: %d\n", inner, *js.MaxConsumers)
	}
	if js.MaxBytesRequired != nil {
		fmt.Fprintf(b, "%smax_bytes_required: %t\n", inner, *js.MaxBytesRequired)
	}
	if js.MemoryMaxStreamBytes != "" {
		fmt.Fprintf(b, "%smemory_max_stream_bytes: %s\n", inner, js.MemoryMaxStreamBytes)
	}
	if js.DiskMaxStreamBytes != "" {
		fmt.Fprintf(b, "%sdisk_max_stream_bytes: %s\n", inner, js.DiskMaxStreamBytes)
	}
	if js.MaxAckPending != nil {
		fmt.Fprintf(b, "%smax_ack_pending: %d\n", inner, *js.MaxAckPending)
	}

	fmt.Fprintf(b, "%s}\n", prefix)
}

func writeLimits(b *strings.Builder, limits *LimitsConfig, indent int) {
	prefix := strings.Repeat("  ", indent)
	inner := strings.Repeat("  ", indent+1)

	fmt.Fprintf(b, "%slimits {\n", prefix)

	if limits.MaxConnections != nil {
		fmt.Fprintf(b, "%smax_connections: %d\n", inner, *limits.MaxConnections)
	}
	if limits.MaxSubscriptions != nil {
		fmt.Fprintf(b, "%smax_subscriptions: %d\n", inner, *limits.MaxSubscriptions)
	}
	if limits.MaxPayload != "" {
		fmt.Fprintf(b, "%smax_payload: %s\n", inner, limits.MaxPayload)
	}
	if limits.MaxLeafnodes != nil {
		fmt.Fprintf(b, "%smax_leafnodes: %d\n", inner, *limits.MaxLeafnodes)
	}

	fmt.Fprintf(b, "%s}\n", prefix)
}

func writeUsers(b *strings.Builder, users []UserConfig, indent int) {
	prefix := strings.Repeat("  ", indent)
	inner := strings.Repeat("  ", indent+1)

	fmt.Fprintf(b, "%susers = [\n", prefix)

	for _, user := range users {
		fmt.Fprintf(b, "%s{\n", inner)
		writeUser(b, &user, indent+2)
		fmt.Fprintf(b, "%s}\n", inner)
	}

	fmt.Fprintf(b, "%s]\n", prefix)
}

func writeUser(b *strings.Builder, user *UserConfig, indent int) {
	prefix := strings.Repeat("  ", indent)

	fmt.Fprintf(b, "%snkey: %s\n", prefix, user.NKey)

	if user.Permissions != nil {
		writePermissions(b, user.Permissions, indent)
	}
}

func writePermissions(b *strings.Builder, perms *PermissionsConfig, indent int) {
	prefix := strings.Repeat("  ", indent)

	fmt.Fprintf(b, "%spermissions {\n", prefix)

	if perms.Publish != nil {
		writePermissionRule(b, "publish", perms.Publish, indent+1)
	}
	if perms.Subscribe != nil {
		writePermissionRule(b, "subscribe", perms.Subscribe, indent+1)
	}

	if perms.AllowResponses != nil && perms.AllowResponses.Enabled {
		writeAllowResponses(b, perms.AllowResponses, indent+1)
	}

	fmt.Fprintf(b, "%s}\n", prefix)
}

func writePermissionRule(b *strings.Builder, name string, rule *PermissionRuleConfig, indent int) {
	prefix := strings.Repeat("  ", indent)
	inner := strings.Repeat("  ", indent+1)

	fmt.Fprintf(b, "%s%s {\n", prefix, name)

	if len(rule.Allow) > 0 {
		fmt.Fprintf(b, "%sallow: [%s]\n", inner, quoteStrings(rule.Allow))
	}
	if len(rule.Deny) > 0 {
		fmt.Fprintf(b, "%sdeny: [%s]\n", inner, quoteStrings(rule.Deny))
	}

	fmt.Fprintf(b, "%s}\n", prefix)
}

func writeAllowResponses(b *strings.Builder, ar *ResponsePermissionConfig, indent int) {
	prefix := strings.Repeat("  ", indent)
	// If neither field is set, emit boolean form
	if ar.MaxMsgs == nil && ar.TTL == nil {
		fmt.Fprintf(b, "%sallow_responses: true\n", prefix)
		return
	}
	// Structured form
	inner := strings.Repeat("  ", indent+1)
	fmt.Fprintf(b, "%sallow_responses {\n", prefix)
	if ar.MaxMsgs != nil {
		fmt.Fprintf(b, "%smax: %d\n", inner, *ar.MaxMsgs)
	}
	if ar.TTL != nil {
		fmt.Fprintf(b, "%sttl: %q\n", inner, *ar.TTL)
	}
	fmt.Fprintf(b, "%s}\n", prefix)
}

func quoteStrings(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}
