/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
*/

package controller

import (
	"crypto/sha256"
	"fmt"
	"testing"
)

func TestParseHashHeader(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "typical first-line header",
			in:   "# hash: abc123\n# Auto-generated\nrest...\n",
			want: "abc123",
		},
		{
			name: "realistic auth.conf as exec'd via cat",
			in: "# hash: b42003cbd25ace935a88dc2803ba47adbfc6cf84c673d5aa2c03da9b6abe713a\n" +
				"# Auto-generated by nats-operator - DO NOT EDIT\n" +
				"# WARNING: no NatsUser resources defined.\n" +
				"authorization {\n  users = []\n}\n",
			want: "b42003cbd25ace935a88dc2803ba47adbfc6cf84c673d5aa2c03da9b6abe713a",
		},
		{
			name: "leading blank line tolerated",
			in:   "\n# hash: deadbeef\nnext\n",
			want: "deadbeef",
		},
		{
			name: "CRLF line endings tolerated",
			in:   "# hash: cafe\r\nnext line\r\n",
			want: "cafe",
		},
		{
			name: "extra whitespace around hash tolerated",
			in:   "#   hash:    spacey   \nnext\n",
			want: "spacey",
		},
		{
			name: "empty input",
			in:   "",
			want: "",
		},
		{
			name: "only whitespace",
			in:   "\n\n\n",
			want: "",
		},
		{
			name: "first non-empty line is not a header → no scan further",
			in:   "accounts {}\n# hash: nope\n",
			want: "",
		},
		{
			name: "header without colon → not recognized",
			in:   "# hash abc\nrest\n",
			want: "",
		},
		{
			name: "header but empty value",
			in:   "# hash:\nrest\n",
			want: "",
		},
		{
			name: "comment that isn't the hash header",
			in:   "# Auto-generated\n# hash: xyz\n",
			want: "",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := parseHashHeader(tc.in)
			if got != tc.want {
				t.Errorf("parseHashHeader(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

// TestFormatAndParseRoundTrip verifies the controller's emitted header is
// exactly what parseHashHeader expects to find inside a pod. This guards
// against drift between the writer (controller) and the reader (parser),
// which is the kind of bug the existing bool-flag fake could not catch.
func TestFormatAndParseRoundTrip(t *testing.T) {
	cases := []string{
		"abc",
		"b42003cbd25ace935a88dc2803ba47adbfc6cf84c673d5aa2c03da9b6abe713a",
		fmt.Sprintf("%x", sha256.Sum256([]byte("anything"))),
	}
	for _, want := range cases {
		header := FormatHashHeader(want)
		body := header + "# Auto-generated\naccounts {}\n"
		if got := parseHashHeader(body); got != want {
			t.Errorf("round trip for %q: got %q from %q", want, got, body)
		}
	}
}
