# This rule is not used by the project natsoperatorexperiment itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over nats.k8s.sandstorm.de.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: natsoperatorexperiment
    app.kubernetes.io/managed-by: kustomize
  name: natsuser-admin-role
rules:
- apiGroups:
  - nats.k8s.sandstorm.de
  resources:
  - natsusers
  verbs:
  - '*'
- apiGroups:
  - nats.k8s.sandstorm.de
  resources:
  - natsusers/status
  verbs:
  - get
