apiVersion: nats.k8s.sandstorm.de/v1alpha1
kind: NatsAccount
metadata:
  labels:
    app.kubernetes.io/name: nats-auth-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-account
spec:
  clusterRef:
    name: main
  allowedUserNamespaces:
    - "^team-.*$"
  jetstream:
    maxMemory: "512Mi"
    maxFile: "1Gi"
    maxStreams: 10
    maxConsumers: 100
  limits:
    maxConnections: 500
    maxPayload: "1Mi"
