apiVersion: nats.k8s.sandstorm.de/v1alpha1
kind: NatsAccount
metadata:
  labels:
    app.kubernetes.io/name: natsoperatorexperiment
    app.kubernetes.io/managed-by: kustomize
  name: natsaccount-sample
spec:
  # TODO(user): Add fields here
