//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountJetStream) DeepCopyInto(out *AccountJetStream) {
	*out = *in
	if in.MaxMemory != nil {
		in, out := &in.MaxMemory, &out.MaxMemory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxFile != nil {
		in, out := &in.MaxFile, &out.MaxFile
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxStreams != nil {
		in, out := &in.MaxStreams, &out.MaxStreams
		*out = new(int64)
		**out = **in
	}
	if in.MaxConsumers != nil {
		in, out := &in.MaxConsumers, &out.MaxConsumers
		*out = new(int64)
		**out = **in
	}
	if in.MaxBytesRequired != nil {
		in, out := &in.MaxBytesRequired, &out.MaxBytesRequired
		*out = new(bool)
		**out = **in
	}
	if in.MemoryMaxStreamBytes != nil {
		in, out := &in.MemoryMaxStreamBytes, &out.MemoryMaxStreamBytes
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DiskMaxStreamBytes != nil {
		in, out := &in.DiskMaxStreamBytes, &out.DiskMaxStreamBytes
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxAckPending != nil {
		in, out := &in.MaxAckPending, &out.MaxAckPending
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountJetStream.
func (in *AccountJetStream) DeepCopy() *AccountJetStream {
	if in == nil {
		return nil
	}
	out := new(AccountJetStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountLimits) DeepCopyInto(out *AccountLimits) {
	*out = *in
	if in.MaxConnections != nil {
		in, out := &in.MaxConnections, &out.MaxConnections
		*out = new(int64)
		**out = **in
	}
	if in.MaxSubscriptions != nil {
		in, out := &in.MaxSubscriptions, &out.MaxSubscriptions
		*out = new(int64)
		**out = **in
	}
	if in.MaxPayload != nil {
		in, out := &in.MaxPayload, &out.MaxPayload
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxLeafnodes != nil {
		in, out := &in.MaxLeafnodes, &out.MaxLeafnodes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountLimits.
func (in *AccountLimits) DeepCopy() *AccountLimits {
	if in == nil {
		return nil
	}
	out := new(AccountLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectReference) DeepCopyInto(out *NamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference.
func (in *NamespacedObjectReference) DeepCopy() *NamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccount) DeepCopyInto(out *NatsAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccount.
func (in *NatsAccount) DeepCopy() *NatsAccount {
	if in == nil {
		return nil
	}
	out := new(NatsAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccountList) DeepCopyInto(out *NatsAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccountList.
func (in *NatsAccountList) DeepCopy() *NatsAccountList {
	if in == nil {
		return nil
	}
	out := new(NatsAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccountSpec) DeepCopyInto(out *NatsAccountSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.UserRules != nil {
		in, out := &in.UserRules, &out.UserRules
		*out = make([]UserRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.JetStream != nil {
		in, out := &in.JetStream, &out.JetStream
		*out = new(AccountJetStream)
		(*in).DeepCopyInto(*out)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(AccountLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccountSpec.
func (in *NatsAccountSpec) DeepCopy() *NatsAccountSpec {
	if in == nil {
		return nil
	}
	out := new(NatsAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccountStatus) DeepCopyInto(out *NatsAccountStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccountStatus.
func (in *NatsAccountStatus) DeepCopy() *NatsAccountStatus {
	if in == nil {
		return nil
	}
	out := new(NatsAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsCluster) DeepCopyInto(out *NatsCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsCluster.
func (in *NatsCluster) DeepCopy() *NatsCluster {
	if in == nil {
		return nil
	}
	out := new(NatsCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsClusterList) DeepCopyInto(out *NatsClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsClusterList.
func (in *NatsClusterList) DeepCopy() *NatsClusterList {
	if in == nil {
		return nil
	}
	out := new(NatsClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsClusterSpec) DeepCopyInto(out *NatsClusterSpec) {
	*out = *in
	if in.ServerRef != nil {
		in, out := &in.ServerRef, &out.ServerRef
		*out = new(WorkloadReference)
		**out = **in
	}
	if in.MonitoringPort != nil {
		in, out := &in.MonitoringPort, &out.MonitoringPort
		*out = new(int32)
		**out = **in
	}
	if in.ExternalURLs != nil {
		in, out := &in.ExternalURLs, &out.ExternalURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsClusterSpec.
func (in *NatsClusterSpec) DeepCopy() *NatsClusterSpec {
	if in == nil {
		return nil
	}
	out := new(NatsClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsClusterStatus) DeepCopyInto(out *NatsClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsClusterStatus.
func (in *NatsClusterStatus) DeepCopy() *NatsClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NatsClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUser) DeepCopyInto(out *NatsUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUser.
func (in *NatsUser) DeepCopy() *NatsUser {
	if in == nil {
		return nil
	}
	out := new(NatsUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUserList) DeepCopyInto(out *NatsUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUserList.
func (in *NatsUserList) DeepCopy() *NatsUserList {
	if in == nil {
		return nil
	}
	out := new(NatsUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUserSpec) DeepCopyInto(out *NatsUserSpec) {
	*out = *in
	out.AccountRef = in.AccountRef
	if in.InboxPrefix != nil {
		in, out := &in.InboxPrefix, &out.InboxPrefix
		*out = new(string)
		**out = **in
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = new(Permissions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUserSpec.
func (in *NatsUserSpec) DeepCopy() *NatsUserSpec {
	if in == nil {
		return nil
	}
	out := new(NatsUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUserStatus) DeepCopyInto(out *NatsUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.ConnectionURLs != nil {
		in, out := &in.ConnectionURLs, &out.ConnectionURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUserStatus.
func (in *NatsUserStatus) DeepCopy() *NatsUserStatus {
	if in == nil {
		return nil
	}
	out := new(NatsUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionRule) DeepCopyInto(out *PermissionRule) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionRule.
func (in *PermissionRule) DeepCopy() *PermissionRule {
	if in == nil {
		return nil
	}
	out := new(PermissionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Permissions) DeepCopyInto(out *Permissions) {
	*out = *in
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(PermissionRule)
		(*in).DeepCopyInto(*out)
	}
	if in.Subscribe != nil {
		in, out := &in.Subscribe, &out.Subscribe
		*out = new(PermissionRule)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowResponses != nil {
		in, out := &in.AllowResponses, &out.AllowResponses
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Permissions.
func (in *Permissions) DeepCopy() *Permissions {
	if in == nil {
		return nil
	}
	out := new(Permissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserRule) DeepCopyInto(out *UserRule) {
	*out = *in
	if in.NamespaceRegex != nil {
		in, out := &in.NamespaceRegex, &out.NamespaceRegex
		*out = new(string)
		**out = **in
	}
	if in.NamespaceLabels != nil {
		in, out := &in.NamespaceLabels, &out.NamespaceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SameNamespace != nil {
		in, out := &in.SameNamespace, &out.SameNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserRule.
func (in *UserRule) DeepCopy() *UserRule {
	if in == nil {
		return nil
	}
	out := new(UserRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadReference.
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}
